apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kotlin-app-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-Client-Version"
    nginx.ingress.kubernetes.io/canary-by-header-value: "v3"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kotlin-app-service
            port:
              number: 8080